### ISSUE TITLE
wiki links

### ISSUE THREAD

**Issue by guruofquality** [pothosware/PothosGPU#2]
Current wiki page says its an SDR wrapper. Even if there is no information, those should be deleted and list a link to the readme will suffice.

Also

* add pothosgpu to list of toolkits in pothos core
* pothos-scripts repo need it added to the script list

**Comment by ncorgan** [comment]
Yeah, I just copy+pasted that this morning. Filling it out locally is how I found the naming issue.

**Comment by ncorgan** [comment]
The wiki page now links to the README. I've added PothosGPU to PothosCore's list of toolkits and synced the sidebars. I don't have permissions for the scripts repo, so I can't push the commit with the change.
